name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  

      - name: Install dependencies
        run: |
          pip install boto3
          pip install requests
          pip install pytest mock

      - name: Run tests for StoreJsonPlaceholderUsers
        run: |
          cd ./Lambda/StoreJsonPlaceholderUsers
          export PYTHONPATH="." 
          python -m unittest discover

      - name: Run tests for ProcessJsonPlaceholderUsers
        run: |
          cd ./Lambda/ProcessJsonPlaceholderUsers
          export PYTHONPATH="."
          python -m unittest discover
